# Malnati/git-report-ops@v1.1.2
name: "Git Report Ops"
description: "Engine GitOps v1.1.1: Fix de newlines e formatação aprimorada da PR."
author: "Ricardo Malnati"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  token:
    description: "GitHub token."
    required: true
  report_file:
    description: "Arquivo Markdown para publicar."
    required: true
  scan_extensions:
    description: "Extensões para assinatura."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  scan_exclude:
    description: "Caminhos ignorados."
    required: false
    default: "node_modules|dist|build|.git|.github"
  report_branch_prefix:
    description: "Prefixo da branch."
    required: false
    default: "audit/report"
  pr_title:
    description: "Título da PR."
    required: false
    default: "🛡️ Automated Audit Report"
  pr_body:
    description: "Corpo base da PR."
    required: false
    default: "Relatório de auditoria gerado automaticamente."
  bot_email:
    description: "Email do bot."
    required: false
    default: "git-report-ops@users.noreply.github.com"

outputs:
  pr_url:
    description: "URL da Pull Request."
    value: ${{ steps.publish.outputs.pr_url }}
  status:
    description: "Status da operação."
    value: ${{ steps.logic_controller.outputs.status }}

runs:
  using: "composite"
  steps:
    # ==================================================================
    # BLOCK 1: INITIALIZATION & VALIDATION (Split)
    # ==================================================================
    
    # 1.0 - Validação de Segurança
    - id: validate_token
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        echo "::group::🔐 Validation: Token"
        if [ -z "$TOKEN" ]; then 
           echo "❌ Error: Input 'token' is missing."
           echo "   Please provide a valid GitHub Token with permissions:"
           echo "   - contents: write"
           echo "   - pull-requests: write"
           exit 1
        fi
        echo "✅ Token present."
        echo "::endgroup::"

    # 1.1 - Validação de Arquivo (Input)
    - id: validate_report
      shell: bash
      env:
        REPORT: ${{ inputs.report_file }}
      run: |
        echo "::group::📄 Validation: Report File"
        if [ ! -f "$REPORT" ]; then 
           echo "❌ Error: Report file not found at: '$REPORT'"
           echo "   Make sure the previous step generated the artifact correctly."
           exit 1
        fi
        echo "✅ Report file found: $REPORT"
        echo "::endgroup::"

    # 1.2 - Configuração de Ambiente Git
    - id: git_config
      shell: bash
      env:
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🔧 Git Config: Identity"
        
        # Configura identidade para este job
        git config user.name "git-report-ops-bot"
        git config user.email "$BOT_EMAIL"
        
        echo "✅ Git identity configured:"
        echo "   Name:  git-report-ops-bot"
        echo "   Email: $BOT_EMAIL"
        echo "::endgroup::"
        
    # ==================================================================
    # BLOCK 2: CIRCUIT BREAKER (Split)
    # ==================================================================

    # 2.0 - Proteção por Nome da Branch
    - id: check_branch
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        PREFIX: ${{ inputs.report_branch_prefix }}
      run: |
        echo "::group::🛡️ Anti-Loop: Branch Name Check"
        echo "Target Branch: $HEAD_REF"
        echo "Report Prefix: $PREFIX"
        
        if [[ "$HEAD_REF" == "$PREFIX"* ]]; then
           echo "🛑 Loop Detected: Running inside a report branch."
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"
        else
           echo "✅ Branch check passed."
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 2.1 - Preparação do Histórico (Fetch)
    # Só roda se o passo anterior não bloqueou
    - id: fetch_history
      if: steps.check_branch.outputs.skip != 'true'
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        echo "::group::📚 Git History: Fetching Context"
        if [ -f .git/shallow ]; then
           echo "⚙️ Shallow repo detected. Fetching depth 1 for author check..."
           git fetch --depth=1 origin "$HEAD_REF" 2>/dev/null || true
        else
           echo "✅ Full history available."
        fi
        echo "::endgroup::"

    # 2.2 - Proteção por Autor do Commit
    # Só roda se o passo 2.0 não bloqueou
    - id: check_author
      if: steps.check_branch.outputs.skip != 'true'
      shell: bash
      env:
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🛡️ Anti-Loop: Commit Author Check"
        
        LAST_AUTHOR=$(git log -1 --pretty=format:'%ae')
        echo "Last Commit Author: $LAST_AUTHOR"
        echo "Bot Email: $BOT_EMAIL"

        if [[ "$LAST_AUTHOR" == "$BOT_EMAIL" ]]; then
           echo "🛑 Loop Detected: Last commit was made by the bot."
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"
        else
           echo "✅ Author check passed."
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 3: IDEMPOTENCY CHECK (Split)
    # ==================================================================

    # 3.0 - Cálculo da Assinatura do Código (Refatorado: Step-by-Step)
    - id: calc_signature
      # Verifica os dois skips do Bloco 2
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true'
      shell: bash
      env:
        EXTS: ${{ inputs.scan_extensions }}
        EXCLUDE: ${{ inputs.scan_exclude }}
      run: |
        echo "::group::🧮 Idempotency: Calculating Signature"
        set -euo pipefail

        # Definição de arquivos temporários
        ALL_FILES="/tmp/files_all.txt"
        EXT_MATCHES="/tmp/files_extensions.txt"
        FINAL_LIST="/tmp/files_final.txt"
        HASH_LIST="/tmp/object_hashes.txt"

        # 1. Listar todos os arquivos do HEAD
        echo "📂 1. Listando arquivos do repositório..."
        git ls-tree -r HEAD --name-only > "$ALL_FILES"
        COUNT_ALL=$(wc -l < "$ALL_FILES")
        echo "   -> Total encontrado: $COUNT_ALL arquivos."

        # 2. Filtrar por Extensão
        # Usa '|| true' para não quebrar o script caso grep não ache nada (exit code 1)
        echo "🔍 2. Filtrando por extensões: .($EXTS)"
        grep -E "\.($EXTS)$" "$ALL_FILES" > "$EXT_MATCHES" || true
        COUNT_EXT=$(wc -l < "$EXT_MATCHES")
        echo "   -> Arquivos compatíveis: $COUNT_EXT"

        # 3. Remover Exclusões
        echo "🗑️ 3. Removendo padrões ignorados: $EXCLUDE"
        grep -vE "$EXCLUDE" "$EXT_MATCHES" > "$FINAL_LIST" || true
        COUNT_FINAL=$(wc -l < "$FINAL_LIST")
        echo "   -> Arquivos para assinatura: $COUNT_FINAL"

        # 4. Calcular Hash dos Objetos
        echo "#️⃣ 4. Gerando hash dos objetos..."
        if [ -s "$FINAL_LIST" ]; then
           # xargs: -a (lê arquivo), -d (delimitador newline), -r (não roda se vazio)
           xargs -a "$FINAL_LIST" -d '\n' -r git hash-object > "$HASH_LIST"
           
           # Calcula MD5 da lista de hashes para gerar assinatura única
           SIGNATURE=$(md5sum "$HASH_LIST" | awk '{print $1}')
        else
           echo "   ⚠️ Aviso: Nenhum arquivo restante para cálculo. Assinatura será 'empty'."
           SIGNATURE="empty"
        fi

        echo "🔑 Content Signature: $SIGNATURE"
        
        # Exporta para ENV
        echo "CODE_SIGNATURE=$SIGNATURE" >> "$GITHUB_ENV"
        echo "::endgroup::"

    # 3.1 - Injeção de Metadados no Relatório
    - id: prep_report
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true'
      shell: bash
      env:
        REPORT: ${{ inputs.report_file }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
      run: |
        echo "::group::📝 Report: Injecting Metadata"
        
        TEMP="/tmp/meta_report.md"
        echo "" > "$TEMP"
        echo "> **Content Signature:** $SIGNATURE" >> "$TEMP"
        echo "> **Source SHA:** $HEAD_SHA" >> "$TEMP"
        echo "> **Data:** $(date -u)" >> "$TEMP"
        echo "" >> "$TEMP"
        cat "$REPORT" >> "$TEMP"
        
        # Substitui arquivo original
        mv "$TEMP" "$REPORT"
        echo "✅ Metadata added to $REPORT"
        echo "::endgroup::"

    # 3.2 - Busca de Histórico (Idempotência)
    - id: check_history
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true'
      shell: bash
      env:
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🕵️ Idempotency: History Search"
        
        # Garante histórico para busca
        if [ -f .git/shallow ]; then 
           echo "⚙️ Unshallowing repo for deep search..."
           git fetch --unshallow 2>/dev/null || true
        fi
        git fetch --all --quiet
        
        SEARCH="> **Content Signature:** $SIGNATURE"
        echo "🔍 Searching for signature in bot commits..."
        
        FOUND=$(git grep -I -F -l "$SEARCH" $(git rev-list --all --author="$BOT_EMAIL") -- "*.md" 2>/dev/null | head -n 1 || true)

        if [ -n "$FOUND" ]; then
           echo "✅ Idempotent match found: $FOUND"
           echo "found=true" >> "$GITHUB_OUTPUT"
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_IDEMPOTENT" >> "$GITHUB_OUTPUT"
           
           # Extrai SHA do commit onde o arquivo foi achado para o próximo passo
           SHA=$(echo "$FOUND" | cut -d':' -f1)
           echo "commit_sha=$SHA" >> "$GITHUB_OUTPUT"
        else
           echo "📝 No match found. Content is new."
           echo "found=false" >> "$GITHUB_OUTPUT"
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 3.3 - Recuperação de URL (Apenas se achou histórico)
    - id: recover_url
      if: steps.check_history.outputs.found == 'true'
      shell: bash
      env:
        COMMIT_SHA: ${{ steps.check_history.outputs.commit_sha }}
      run: |
        echo "::group::🔗 Idempotency: Recovering PR URL"
        
        # Tenta achar a branch remota que contem este commit
        BRANCH=$(git branch -r --contains "$COMMIT_SHA" | grep "origin/ops/" | head -n 1 | sed 's/origin\///' | xargs)
        
        if [ -n "$BRANCH" ]; then
           echo "🔍 Found branch: $BRANCH"
           # Tenta achar a PR aberta para esta branch
           URL=$(gh pr list --head "$BRANCH" --json url -q .[0].url)
           
           if [ -n "$URL" ]; then
              echo "✅ Recovered PR URL: $URL"
              echo "pr_url=$URL" >> "$GITHUB_OUTPUT"
           else
              echo "⚠️ Branch found but no open PR detected."
           fi
        else
           echo "⚠️ Could not resolve branch from commit $COMMIT_SHA."
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 4: PUBLISH (BRANCH & PR MANAGEMENT)
    # ==================================================================
    - id: publish
      if: steps.circuit_breaker.outputs.skip != 'true' && steps.idempotency.outputs.skip != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPORT_FILE: ${{ inputs.report_file }}
        HEAD_REF: ${{ github.head_ref }}
        PR_NUM: ${{ github.event.pull_request.number }}
        PREFIX: ${{ inputs.report_branch_prefix }}
        TITLE: ${{ inputs.pr_title }}
        USER_BODY: ${{ inputs.pr_body }}
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "::group::🚀 Publishing Report"
        
        REPORT_BRANCH="${PREFIX}/${HEAD_REF}"
        
        # 1. Git Operations (Branch & Push)
        git checkout "$HEAD_REF"
        git checkout -B "$REPORT_BRANCH"
        git add "$REPORT_FILE"
        git commit -m "docs: automated report update [skip ci]"
        git push -f origin "$REPORT_BRANCH"
        
        # 2. Construct PR Body (File-based to fix newlines)
        BODY_FILE="/tmp/pr_body.md"
        
        cat <<EOF > "$BODY_FILE"
        $USER_BODY

        ---
        ### 🛡️ Metadados de Rastreabilidade
        > Esta PR contém artefatos gerados automaticamente para a revisão da PR original.

        | 🏷️ Chave | ℹ️ Valor |
        | :--- | :--- |
        | **PR Origem** | #$PR_NUM (\`$HEAD_REF\`) |
        | **Commit Base** | \`$HEAD_SHA\` |
        | **Assinatura** | \`$SIGNATURE\` |
        | **Data (UTC)** | $(date -u) |

        EOF
        
        echo "📡 Managing Pull Request..."
        
        # 3. Create/Update PR
        gh pr create \
          --base "$HEAD_REF" \
          --head "$REPORT_BRANCH" \
          --title "$TITLE" \
          --body-file "$BODY_FILE" || true
          
        PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
        
        # Force Body Update (for existing PRs)
        gh pr edit "$PR_URL" --body-file "$BODY_FILE" || true
        
        echo "✅ PR Link: $PR_URL"
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "status=PUBLISHED" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 5: LOGIC CONTROLLER (OUTPUT SUMMARY)
    # ==================================================================
    - id: logic_controller
      shell: bash
      if: always()
      env:
        S1: ${{ steps.circuit_breaker.outputs.reason }}
        S2: ${{ steps.idempotency.outputs.reason }}
        S3: ${{ steps.publish.outputs.status }}
      run: |
        FINAL_STATUS="UNKNOWN"
        if [ -n "$S3" ]; then FINAL_STATUS="$S3";
        elif [ -n "$S2" ]; then FINAL_STATUS="$S2";
        elif [ -n "$S1" ]; then FINAL_STATUS="$S1";
        fi
        echo "status=$FINAL_STATUS" >> "$GITHUB_OUTPUT"
