# Malnati/git-report-ops@v1.3.17
name: "Git Report Ops"
description: "Engine de auditoria que assina o conteúdo, detecta renames e envia notificações padronizadas para Pull Requests."
author: "Ricardo Malnati"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  token:
    description: "GitHub token."
    required: true
  report_file:
    description: "Arquivo Markdown."
    required: true
  caller_id:
    required: false
    default: "unknown-workflow"
  scan_extensions:
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  scan_exclude:
    required: false
    default: "node_modules|dist|build|.git|.github"
  report_branch_prefix:
    required: false
    default: "ops/files"
  pr_title:
    required: false
    default: "🛡️ Automated Pull Request"
  pr_body:
    required: false
    default: "Relatório de auditoria."
  bot_email:
    required: false
    default: "git-report-ops@users.noreply.github.com"
  pr_template_path:
    required: true
    default: ""
  notification_id:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: step_validate_inputs
      name: "🔧 Setup & Input Validation"
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPORT: ${{ inputs.report_file }}
        CALLER_ID: ${{ inputs.caller_id }}
        SCAN_EXTENSIONS: ${{ inputs.scan_extensions }}
        SCAN_EXCLUDE: ${{ inputs.scan_exclude }}
        REPORT_BRANCH_PREFIX: ${{ inputs.report_branch_prefix }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY: ${{ inputs.pr_body }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        PR_TEMPLATE_PATH: ${{ inputs.pr_template_path }}
        NOTIFICATION_ID: ${{ inputs.notification_id }}
      run: |
        echo "::group::🔧 Setup & Input Validation"

        # token (obrigatório)
        if [ -z "$TOKEN" ]; then
          echo "❌ [token] Obrigatório e não informado. Sem este token a Action não consegue chamar a API do GitHub (gh CLI, criação/edição de PR e comentários)."
          echo "   ➜ Defina 'token' com 'secrets.GITHUB_TOKEN' ou um PAT com permissões de leitura/escrita em PRs."
          exit 1
        else
          echo "✅ [token] Informado. A Action poderá criar/atualizar PRs e publicar comentários."
        fi

        # report_file (obrigatório)
        if [ -z "$REPORT" ]; then
          echo "❌ [report_file] Caminho não informado. A Action precisa de um arquivo Markdown para anexar ao PR."
          echo "   ➜ Gere o relatório no job anterior e passe o caminho em 'report_file' (ex.: 'reports/pmd-report.md')."
          exit 1
        elif [ ! -f "$REPORT" ]; then
          echo "❌ [report_file] Arquivo '$REPORT' não encontrado."
          echo "   ➜ Verifique o caminho informado em 'report_file' e garanta que o arquivo é criado antes desta Action."
          exit 1
        else
          echo "✅ [report_file] Encontrado em '$REPORT'. Será usado como base do relatório publicado."
        fi

        # caller_id (opcional)
        if [ -z "$CALLER_ID" ] || [ "$CALLER_ID" = "unknown-workflow" ]; then
          echo "ℹ️ [caller_id] Não informado. Será usado 'unknown-workflow' como identificador do workflow de origem."
          echo "   ➜ Defina 'caller_id' (ex.: 'pmd-audit', 'eslint-audit') para rastrear qual workflow/job gerou o relatório."
        else
          echo "✅ [caller_id] Definido como '$CALLER_ID'. Será incluído na assinatura/meta do relatório e nas notificações."
        fi

        # scan_extensions (opcional)
        if [ -z "$SCAN_EXTENSIONS" ]; then
          echo "ℹ️ [scan_extensions] Não informado. A assinatura poderá considerar todos os arquivos, o que pode aumentar o custo da varredura."
          echo "   ➜ Recomenda-se definir uma lista como 'ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml' para focar em código-fonte."
        else
          echo "ℹ️ [scan_extensions] Usando lista: '$SCAN_EXTENSIONS'."
          echo "   ➜ Ajuste 'scan_extensions' para incluir/remover extensões que devem impactar a assinatura de conteúdo."
        fi

        # scan_exclude (opcional)
        if [ -z "$SCAN_EXCLUDE" ]; then
          echo "ℹ️ [scan_exclude] Não informado. Nenhum diretório será excluído da análise, o que pode deixá-la mais lenta."
          echo "   ➜ Defina 'scan_exclude' (ex.: 'node_modules|dist|build|.git|.github') para ignorar pastas de build/dependências."
        else
          echo "ℹ️ [scan_exclude] Usando padrão de exclusão: '$SCAN_EXCLUDE'."
          echo "   ➜ Ajuste este valor se quiser incluir ou remover diretórios ignorados na assinatura."
        fi

        # report_branch_prefix (opcional)
        if [ -z "$REPORT_BRANCH_PREFIX" ]; then
          echo "ℹ️ [report_branch_prefix] Não informado. Branches de relatório serão criados sem prefixo dedicado, podendo conflitar com branches de desenvolvimento."
          echo "   ➜ Defina um prefixo (ex.: 'audit/report') para isolar branches de relatório: '<prefix>/<branch_origem>'."
        else
          echo "ℹ️ [report_branch_prefix] Usando prefixo: '$REPORT_BRANCH_PREFIX'."
          echo "   ➜ Os branches de relatório serão criados como '${REPORT_BRANCH_PREFIX}/<branch_de_origem>'."
        fi

        # pr_title (opcional)
        if [ -z "$PR_TITLE" ]; then
          echo "ℹ️ [pr_title] Não informado. O PR poderá ser criado sem título claro, dificultando a leitura na lista de PRs."
          echo "   ➜ Defina 'pr_title' com um título descritivo (ex.: '🛡️ Automated Audit Report')."
        else
          echo "ℹ️ [pr_title] Título configurado como: '$PR_TITLE'."
          echo "   ➜ Este valor será usado como título dos PRs de relatório."
        fi

        # pr_body (opcional)
        if [ -z "$PR_BODY" ]; then
          echo "ℹ️ [pr_body] Não informado. Apenas o conteúdo gerado pelo template será usado no corpo do PR."
          echo "   ➜ Defina 'pr_body' se quiser incluir um texto fixo adicional (ex.: instruções para revisores)."
        else
          echo "ℹ️ [pr_body] Texto base informado. Ele será injetado no template do corpo do PR."
        fi

        # bot_email (opcional, mas crítico para loop protection)
        if [ -z "$BOT_EMAIL" ]; then
          echo "ℹ️ [bot_email] Não informado. O git usará o email padrão do ambiente e isso pode quebrar a proteção de loop baseada no autor."
          echo "   ➜ Defina 'bot_email' (ex.: 'git-report-ops@users.noreply.github.com') para: "
          echo "      - identificar os commits do bot; "
          echo "      - permitir que o circuito anti-loop funcione corretamente."
        else
          echo "ℹ️ [bot_email] Usando: '$BOT_EMAIL'."
          echo "   ➜ Este email será configurado como autor dos commits e usado na verificação de loops."
        fi
        git config user.name "git-report-ops-bot"
        git config user.email "$BOT_EMAIL"

        # pr_template_path (obrigatório)
        if [ -z "$PR_TEMPLATE_PATH" ]; then
          echo "❌  [pr_template_path] Não informado."
          echo "   ➜ Defina 'pr_template_path' com o caminho de um template customizado para personalizar o corpo do PR."
          exit 1;
        else
          if [ -f "$PR_TEMPLATE_PATH" ]; then
            echo "ℹ️ [pr_template_path] Template customizado encontrado em '$PR_TEMPLATE_PATH'."
            echo "   ➜ Ele será usado por 'envsubst' para gerar o corpo do PR."
          else
            echo "⚠️ [pr_template_path] Caminho informado ('$PR_TEMPLATE_PATH'), mas arquivo não existe."
            echo "   ➜ O template padrão será usado. Verifique o caminho ou inclua o arquivo no repositório."
          fi
        fi

        # notification_id (opcional)
        if [ -z "$NOTIFICATION_ID" ]; then
          echo "ℹ️ [notification_id] Não informado. Será gerado um identificador derivado de 'caller_id'."
          echo "   ➜ Use 'notification_id' se quiser controlar manualmente o agrupamento de comentários (ex.: evitar sobrescrever mensagens entre execuções diferentes)."
        else
          echo "ℹ️ [notification_id] Definido como: '$NOTIFICATION_ID'."
          echo "   ➜ Este valor será usado como chave de agrupamento para comentários na PR."
        fi

        echo "✅ Input validation complete."
        echo "::endgroup::"

    - id: step_resolve_ids
      name: "ℹ Resolve IDs"
      shell: bash
      env:
        INPUT_ID: ${{ inputs.notification_id }}
        CALLER: ${{ inputs.caller_id }}
      run: |
        FINAL_ID="git-report-ops-$CALLER";
        if [ -n "$INPUT_ID" ]; 
            then FINAL_ID="$INPUT_ID";       
        fi
        echo "notify_id=$FINAL_ID" >> "$GITHUB_OUTPUT"
        echo "inputs.caller_id: $FINAL_ID"
        echo "✅ notify_id: $FINAL_ID"
        echo "::endgroup::"

    - id: branch_convention
      name: "🪾 Branch Convention"
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        echo "::group::🪾 Create branch due to it does not exist yet;"
        echo "head_ref: $HEAD_REF"
        git fetch --all --prune
        LATEST_SHA="$(git rev-list --all -n 1)"
        CUSTOM_SUFFIX="${LATEST_SHA: -10}"
        PREFIX="ops/report/latest/${CUSTOM_SUFFIX}"
        echo "latest_sha: $LATEST_SHA"
        echo "custom_suffix: $CUSTOM_SUFFIX"
        echo "report_branch_prefix: $PREFIX"
        REPORT_BRANCH="${PREFIX}/${HEAD_REF}"
        echo "report_branch: $REPORT_BRANCH"
        if [ "$HEAD_REF" = "$REPORT_BRANCH" ]; then
          echo "✅ Já está na própria report branch: $REPORT_BRANCH. Nada a fazer."
          echo "report_branch=$REPORT_BRANCH" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"
          exit 0
        fi
        if git show-ref --verify --quiet "refs/heads/$REPORT_BRANCH"; then
          echo "⚠️ Branch já existe: $REPORT_BRANCH"
        else
          git checkout "$HEAD_REF"
          git checkout -b "$REPORT_BRANCH"
          echo "✅ Report branch criada: $REPORT_BRANCH"
        fi
        echo "report_branch=$REPORT_BRANCH" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    - id: latest_commit_verify
      name: "🔎 Latest Commit Verify"
      shell: bash
      env:
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🔎 Verify latest commit owner and branch"
        git fetch --all --prune
        LATEST_SHA="$(git rev-list --all -n 1)"
        CURRENT_SHA="$(git rev-parse HEAD)"
        CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
        COMMIT_AUTHOR_RAW="$(git show -s --format='%an|%ae' "$LATEST_SHA")"
        COMMIT_AUTHOR_NAME="${COMMIT_AUTHOR_RAW%%|*}"
        COMMIT_AUTHOR_EMAIL="${COMMIT_AUTHOR_RAW##*|}"
        echo "latest_sha: $LATEST_SHA"
        echo "current_sha: $CURRENT_SHA"
        echo "current_branch: $CURRENT_BRANCH"
        echo "commit_author_name: $COMMIT_AUTHOR_NAME"
        echo "commit_author_email: $COMMIT_AUTHOR_EMAIL"
        echo "bot_email: $BOT_EMAIL"
        is_bot_commit=false
        if [ "$COMMIT_AUTHOR_EMAIL" = "$BOT_EMAIL" ]; then
          is_bot_commit=true
        fi
        is_latest_on_current_branch=false
        if [ "$LATEST_SHA" = "$CURRENT_SHA" ]; then
          is_latest_on_current_branch=true
        fi
        if [ "$is_bot_commit" = true ] && [ "$is_latest_on_current_branch" = true ]; then
          echo "✅ Último commit do repositório já é do bot nesta mesma branch. Nada a fazer."
          echo "::endgroup::"
          exit 0
        fi
        echo "::endgroup::"

    # Faz o commit do arquivo informado nesta mesma report_branch 
    - id: commit_report
      name: "📝 Commit Report File"
      shell: bash
      env:
        REPORT: ${{ inputs.report_file }}
        REPORT_BRANCH: ${{ steps.branch_convention.outputs.report_branch }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        BOT_NAME: ${{ inputs.bot_name }}
      run: |
        echo "::group::📝 Commit report file"
        echo "report_branch: $REPORT_BRANCH"
        echo "report_file: $REPORT"
        git checkout "$REPORT_BRANCH"
        if [ ! -f "$REPORT" ]; then
          echo "❌ Arquivo de relatório não encontrado: $REPORT"
          echo "::endgroup::"
          exit 1
        fi
        git config user.email "$BOT_EMAIL"
        if [ -n "${BOT_NAME:-}" ]; then
          git config user.name "$BOT_NAME"
        fi
        git add "$REPORT"
        if git diff --cached --quiet; then
          echo "⚠️ Nenhuma alteração para commitar em $REPORT"
          echo "::endgroup::"
          exit 0
        fi
        git commit -m "chore(report): update audit report"
        git push origin "$REPORT_BRANCH"
        COMMIT_SHA="$(git rev-parse HEAD)"
        echo "commit_sha=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
        echo "✅ Report commit realizado em $REPORT_BRANCH (commit $COMMIT_SHA)"
        echo "::endgroup::"

    - id: notify_branch_convention
      name: "🔔 Notify Branch Convention"
      uses: Malnati/pr-comment@v8.0.0
      env:
        REPORT: ${{ inputs.report_file }}
        BODY_MESSAGE: "A branch do arquivo ${{ inputs.report_file }} é ${{ steps.branch_convention.outputs.report_branch }} e o commit referente a inclusão deste arquivo é ${{steps.commit_report.outputs.commit_sha}}"
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ github.event.pull_request.number }}
        use_raw_body: "true"

    - id: analyze_pr_status
      name: "🔍 Análise de PR Existente"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        COMMIT_SHA: ${{ steps.commit_report.outputs.commit_sha }}
        REPORT_BRANCH: ${{ steps.branch_convention.outputs.report_branch }}
      run: |
        echo "::group::🔍 Analyzing Existing PR"
        echo "REPORT_BRANCH: $REPORT_BRANCH"
        if [ -n "$REPORT_BRANCH" ]; then
           PR_DATA=$(gh pr list --head "$REPORT_BRANCH" --state all --json state,url,mergedAt --limit 1)
           echo "PR_DATA bruto:"
           echo "$PR_DATA"
           STATE=$(echo "$PR_DATA" | jq -r '.[0].state')
           URL=$(echo "$PR_DATA" | jq -r '.[0].url')
           MERGED=$(echo "$PR_DATA" | jq -r '.[0].mergedAt')
           echo "existing_url=$URL" >> "$GITHUB_OUTPUT"
           echo "pr_state=$STATE" >> "$GITHUB_OUTPUT"
           if [ "$STATE" == "OPEN" ]; then
              echo "🟢 PR is OPEN."
              echo "status_code=OPEN_EXISTING" >> "$GITHUB_OUTPUT"
           elif [ "$STATE" == "CLOSED" ] && [ "$MERGED" == "null" ]; then
              echo "🔴 PR is CLOSED (Unmerged)."
              echo "status_code=CLOSED_UNMERGED" >> "$GITHUB_OUTPUT"
           else
              echo "⚪ PR is Merged/Missing."
              echo "status_code=PREVIOUSLY_MERGED" >> "$GITHUB_OUTPUT"
           fi
        else
           echo "⚠️ Branch not found. Treating as new."
           echo "status_code=NOT_FOUND" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    - id: publish
      name: "🚀 Publishing"
      if: steps.analyze_pr_status.outputs.status_code == 'NOT_FOUND'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        HEAD_REF: ${{ github.head_ref }}
        REPORT_BRANCH: ${{ steps.branch_convention.outputs.report_branch }}
        REPORT: ${{ inputs.report_file }}
        TITLE: ${{ inputs.pr_title }}
        PR_TEMPLATE_PATH: ${{ inputs.pr_template_path }}
      run: |
        echo "::group::🚀 Publishing"      
        if gh pr create --base "$HEAD_REF" --head "$REPORT_BRANCH" --title "$TITLE" --body-file "$PR_TEMPLATE_PATH"; then
           echo "✅ New PR created."
        else
           echo "ℹ️ PR creation skipped. Updating existing..."
        fi
        PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
        echo "PR_URL: $PR_URL"
        if ! gh pr edit "$PR_URL" --body-file "$BODY_FILE"; then
          echo "🔴 Erro ao atualizar PR em $PR_URL com o arquivo $BODY_FILE" >&2
        fi
        echo "pr_url: $PR_URL"
        echo "::endgroup::"
