# Malnati/git-report-ops@v1.3.0
name: "Git Report Ops"
description: "Engine v1.3.0: Gestão completa de ciclo de vida de auditoria, idempotência global e comunicação bidirecional."
author: "Ricardo Malnati"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  token:
    description: "GitHub token."
    required: true
  report_file:
    description: "Arquivo Markdown para publicar."
    required: true
  caller_id:
    description: "Identificador do chamador (ex: workflow filename) para rastreabilidade."
    required: false
    default: "unknown-workflow"
  
  # Assinatura
  scan_extensions:
    description: "Extensões para assinatura."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  scan_exclude:
    description: "Caminhos ignorados."
    required: false
    default: "node_modules|dist|build|.git|.github"
  
  # Config PR
  report_branch_prefix:
    description: "Prefixo da branch."
    required: false
    default: "audit/report"
  pr_title:
    description: "Título da PR."
    required: false
    default: "🛡️ Automated Audit Report"
  pr_body:
    description: "Corpo base da PR."
    required: false
    default: "Relatório de auditoria gerado automaticamente."
  bot_email:
    description: "Email do bot."
    required: false
    default: "git-report-ops@users.noreply.github.com"
  
  # Templates (Opcionais - Se não informados, a action usará seus defaults internos)
  pr_template_path:
    description: "Caminho customizado para o corpo da PR de relatório."
    required: false
    default: ""

outputs:
  pr_url:
    description: "URL da Pull Request."
    value: ${{ steps.controller.outputs.pr_url }}
  status:
    description: "Status final."
    value: ${{ steps.controller.outputs.status }}

runs:
  using: "composite"
  steps:
    # ==================================================================
    # BLOCK 1: SETUP & VALIDATION
    # ==================================================================
    - id: validate_inputs
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPORT: ${{ inputs.report_file }}
      run: |
        echo "::group::🔧 Setup: Input Validation"
        if [ -z "$TOKEN" ]; then echo "❌ Error: Token missing."; exit 1; fi
        if [ ! -f "$REPORT" ]; then echo "❌ Error: Report file missing."; exit 1; fi
        
        git config user.name "git-report-ops-bot"
        git config user.email "${{ inputs.bot_email }}"
        echo "✅ Setup complete."
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 2: CIRCUIT BREAKER
    # ==================================================================
    - id: circuit_breaker
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        PREFIX: ${{ inputs.report_branch_prefix }}
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🛡️ Loop Protection"
        # 1. Branch Check
        if [[ "$HEAD_REF" == "$PREFIX"* ]]; then
           echo "🛑 Loop: Inside report branch."
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"
           exit 0
        fi
        # 2. Author Check
        if [ -f .git/shallow ]; then git fetch --depth=1 origin "$HEAD_REF" 2>/dev/null || true; fi
        LAST=$(git log -1 --pretty=format:'%ae')
        if [[ "$LAST" == "$BOT_EMAIL" ]]; then
           echo "🛑 Loop: Bot commit detected."
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"
           exit 0
        fi
        echo "✅ Safe."
        echo "skip=false" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 3: IDEMPOTENCY & HISTORY SEARCH
    # ==================================================================
    
    # 3.0 - Assinatura
    - id: calc_signature
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        EXTS: ${{ inputs.scan_extensions }}
        EXCLUDE: ${{ inputs.scan_exclude }}
      run: |
        echo "::group::🧮 Signature Calculation"
        set -euo pipefail
        LIST_FILE="/tmp/file_list.txt"
        git ls-tree -r HEAD --name-only | grep -E "\.($EXTS)$" | grep -vE "$EXCLUDE" > "$LIST_FILE" || true
        
        if [ -s "$LIST_FILE" ]; then
           xargs -a "$LIST_FILE" -d '\n' -r git hash-object > /tmp/hashes.txt
           SIGNATURE=$(md5sum /tmp/hashes.txt | awk '{print $1}')
        else
           SIGNATURE="empty"
        fi
        echo "CODE_SIGNATURE=$SIGNATURE" >> "$GITHUB_ENV"
        echo "🔑 Signature: $SIGNATURE"
        echo "::endgroup::"

    # 3.1 - Busca Histórica (Global com Filtro de Chamador)
    - id: search_history
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        CALLER: ${{ inputs.caller_id }}
      run: |
        echo "::group::🕵️ Idempotency Search"
        if [ -f .git/shallow ]; then git fetch --unshallow 2>/dev/null || true; fi
        git fetch --all --quiet
        
        # Busca: Assinatura + Caller ID
        SEARCH_SIG="> **Content Signature:** $SIGNATURE"
        # SEARCH_CALLER="> **Caller ID:** $CALLER" # Opcional: refinar busca se necessário
        
        FOUND=$(git grep -I -F -l "$SEARCH_SIG" $(git rev-list --all --author="$BOT_EMAIL") -- "*.md" 2>/dev/null | head -n 1 || true)

        if [ -n "$FOUND" ]; then
           echo "✅ Match found: $FOUND"
           SHA=$(echo "$FOUND" | cut -d':' -f1)
           echo "found=true" >> "$GITHUB_OUTPUT"
           echo "commit_sha=$SHA" >> "$GITHUB_OUTPUT"
        else
           echo "📝 New content detected."
           echo "found=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 3.2 - Análise de PR Existente (Lógica 4.2 e 4.3)
    - id: analyze_pr_status
      if: steps.search_history.outputs.found == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        COMMIT_SHA: ${{ steps.search_history.outputs.commit_sha }}
        PREFIX: ${{ inputs.report_branch_prefix }}
      run: |
        echo "::group::🔍 Analyzing Existing PR"
        TARGET=$(git branch -r --contains "$COMMIT_SHA" | grep "$PREFIX" | head -n 1 | sed 's/origin\///' | xargs || true)
        
        if [ -n "$TARGET" ]; then
           PR_DATA=$(gh pr list --head "$TARGET" --state all --json state,url,mergedAt --limit 1)
           STATE=$(echo "$PR_DATA" | jq -r '.[0].state')
           URL=$(echo "$PR_DATA" | jq -r '.[0].url')
           MERGED=$(echo "$PR_DATA" | jq -r '.[0].mergedAt')
           
           echo "existing_url=$URL" >> "$GITHUB_OUTPUT"
           
           if [ "$STATE" == "OPEN" ]; then
              echo "🟢 PR is OPEN."
              echo "status_code=OPEN_EXISTING" >> "$GITHUB_OUTPUT"
           elif [ "$STATE" == "CLOSED" ] && [ "$MERGED" == "null" ]; then
              echo "🔴 PR is CLOSED (Unmerged)."
              echo "status_code=CLOSED_UNMERGED" >> "$GITHUB_OUTPUT"
           else
              echo "⚪ PR is Merged/Missing."
              echo "status_code=PREVIOUSLY_MERGED" >> "$GITHUB_OUTPUT"
           fi
        else
           echo "⚠️ Branch not found. Treating as new."
           echo "status_code=NOT_FOUND" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 4: COMMUNICATION (PR A - NOTIFICATIONS)
    # ==================================================================

    # 4.1 - Notificar PR Aberta (Cenário 4.2)
    - name: Notify Existing Open
      if: steps.analyze_pr_status.outputs.status_code == 'OPEN_EXISTING'
      uses: Malnati/pr-comment@v7.0.0
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ github.event.pull_request.number }}
        message_id: "git-report-ops-${{ inputs.caller_id }}"
        template_path: ${{ github.action_path }}/templates/notify-found-open.md
        variables: |
          {
            "SIGNATURE": "${{ env.CODE_SIGNATURE }}",
            "EXISTING_PR_URL": "${{ steps.analyze_pr_status.outputs.existing_url }}"
          }

    # 4.2 - Notificar PR Fechada (Cenário 4.3)
    - name: Notify Existing Closed
      if: steps.analyze_pr_status.outputs.status_code == 'CLOSED_UNMERGED'
      uses: Malnati/pr-comment@v7.0.0
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ github.event.pull_request.number }}
        message_id: "git-report-ops-${{ inputs.caller_id }}"
        template_path: ${{ github.action_path }}/templates/notify-found-closed.md
        variables: |
          {
            "SIGNATURE": "${{ env.CODE_SIGNATURE }}",
            "EXISTING_PR_URL": "${{ steps.analyze_pr_status.outputs.existing_url }}"
          }

    # 4.3 - Notificar Início de Novo Relatório (Cenário 5 - Início)
    - name: Notify New Start
      if: steps.search_history.outputs.found != 'true' || steps.analyze_pr_status.outputs.status_code == 'NOT_FOUND'
      uses: Malnati/pr-comment@v7.0.0
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ github.event.pull_request.number }}
        message_id: "git-report-ops-${{ inputs.caller_id }}"
        template_path: ${{ github.action_path }}/templates/notify-new-start.md
        variables: |
          {
            "SIGNATURE": "${{ env.CODE_SIGNATURE }}"
          }

    # ==================================================================
    # BLOCK 5: PUBLISH (NEW REPORT)
    # ==================================================================
    
    # 5.0 - Prepara Arquivos e Corpo da PR
    - id: prepare_files
      if: steps.search_history.outputs.found != 'true' || steps.analyze_pr_status.outputs.status_code == 'NOT_FOUND'
      shell: bash
      env:
        REPORT: ${{ inputs.report_file }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        CALLER: ${{ inputs.caller_id }}
        PR_NUM: ${{ github.event.pull_request.number }}
        HEAD_REF: ${{ github.head_ref }}
        USER_BODY: ${{ inputs.pr_body }}
        CUSTOM_TEMPLATE: ${{ inputs.pr_template_path }}
        DEFAULT_TEMPLATE: ${{ github.action_path }}/templates/pr-body-report.md
      run: |
        echo "::group::📝 Prep Files"
        
        # 1. Injeção de Metadata no Arquivo de Relatório (Item 6)
        TEMP="/tmp/meta.md"
        echo "" > "$TEMP"
        echo "> **Content Signature:** $SIGNATURE" >> "$TEMP"
        echo "> **Caller ID:** $CALLER" >> "$TEMP"
        echo "> **Source SHA:** $HEAD_SHA" >> "$TEMP"
        echo "> **Data:** $(date -u)" >> "$TEMP"
        echo "" >> "$TEMP"
        cat "$REPORT" >> "$TEMP"
        mv "$TEMP" "$REPORT"

        # 2. Seleção do Template do Corpo da PR
        if [[ -n "$CUSTOM_TEMPLATE" && -f "$CUSTOM_TEMPLATE" ]]; then
           TEMPLATE_SOURCE="$CUSTOM_TEMPLATE"
        else
           TEMPLATE_SOURCE="$DEFAULT_TEMPLATE"
        fi

        # 3. Processamento do Template (PR B)
        export USER_BODY PR_NUM HEAD_REF CALLER SIGNATURE
        PR_BODY_FILE="/tmp/pr_b_body.md"
        envsubst < "$TEMPLATE_SOURCE" > "$PR_BODY_FILE"
        
        # Adiciona assinatura oculta no corpo da PR também
        echo "" >> "$PR_BODY_FILE"
        echo "" >> "$PR_BODY_FILE"
        
        echo "pr_body_file=$PR_BODY_FILE" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # 5.1 - Publish (Git Ops)
    - id: publish
      if: steps.search_history.outputs.found != 'true' || steps.analyze_pr_status.outputs.status_code == 'NOT_FOUND'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        HEAD_REF: ${{ github.head_ref }}
        PREFIX: ${{ inputs.report_branch_prefix }}
        REPORT: ${{ inputs.report_file }}
        TITLE: ${{ inputs.pr_title }}
        BODY_FILE: ${{ steps.prepare_files.outputs.pr_body_file }}
      run: |
        echo "::group::🚀 Publishing"
        REPORT_BRANCH="${PREFIX}/${HEAD_REF}"
        
        git checkout "$HEAD_REF"
        git checkout -B "$REPORT_BRANCH"
        git add "$REPORT"
        git commit -m "docs: automated report [skip ci]"
        git push -f origin "$REPORT_BRANCH"
        
        gh pr create --base "$HEAD_REF" --head "$REPORT_BRANCH" --title "$TITLE" --body-file "$BODY_FILE" || true
        PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
        gh pr edit "$PR_URL" --body-file "$BODY_FILE" || true
        
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "status=PUBLISHED" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # 4.4 - Notificar Sucesso/Link (Cenário 5 - Fim)
    - name: Notify Success
      if: steps.publish.outputs.status == 'PUBLISHED'
      uses: Malnati/pr-comment@v7.0.0
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ github.event.pull_request.number }}
        message_id: "git-report-ops-${{ inputs.caller_id }}"
        template_path: ${{ github.action_path }}/templates/notify-new-success.md
        variables: |
          {
            "SIGNATURE": "${{ env.CODE_SIGNATURE }}",
            "NEW_PR_URL": "${{ steps.publish.outputs.pr_url }}"
          }

    # ==================================================================
    # BLOCK 6: CONTROLLER
    # ==================================================================
    - id: controller
      shell: bash
      if: always()
      env:
        S3: ${{ steps.publish.outputs.status }}
        URL: ${{ steps.publish.outputs.pr_url }}
        URL_EXIST: ${{ steps.analyze_pr_status.outputs.existing_url }}
      run: |
        if [ -n "$S3" ]; then FINAL="$S3"; else FINAL="SKIPPED"; fi
        if [ -n "$URL" ]; then FURL="$URL"; else FURL="$URL_EXIST"; fi
        echo "status=$FINAL" >> "$GITHUB_OUTPUT"
        echo "pr_url=$FURL" >> "$GITHUB_OUTPUT"
