# Malnati/git-report-ops@v1.1.2
name: "Git Report Ops"
description: "Engine GitOps v1.1.2: Modular, com validação passo-a-passo e templates customizáveis."
author: "Ricardo Malnati"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  token:
    description: "GitHub token."
    required: true
  report_file:
    description: "Arquivo Markdown para publicar."
    required: true
  scan_extensions:
    description: "Extensões para assinatura."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  scan_exclude:
    description: "Caminhos ignorados."
    required: false
    default: "node_modules|dist|build|.git|.github"
  report_branch_prefix:
    description: "Prefixo da branch."
    required: false
    default: "audit/report"
  pr_title:
    description: "Título da PR."
    required: false
    default: "🛡️ Automated Audit Report"
  pr_body:
    description: "Corpo base da PR."
    required: false
    default: "Relatório de auditoria gerado automaticamente."
  bot_email:
    description: "Email do bot."
    required: false
    default: "git-report-ops@users.noreply.github.com"
  pr_template_path:
    description: "Caminho para um template Markdown customizado."
    required: false
    default: ""

outputs:
  pr_url:
    description: "URL da Pull Request."
    value: ${{ steps.publish.outputs.pr_url }}
  status:
    description: "Status da operação."
    value: ${{ steps.logic_controller.outputs.status }}

runs:
  using: "composite"
  steps:
    # ==================================================================
    # BLOCK 1: INITIALIZATION & VALIDATION
    # ==================================================================
    
    # 1.0 - Validação de Segurança
    - id: validate_token
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        echo "::group::🔐 Validation: Token"
        if [ -z "$TOKEN" ]; then 
           echo "❌ Error: Input 'token' is missing."
           exit 1
        fi
        echo "✅ Token present."
        echo "::endgroup::"

    # 1.1 - Validação de Arquivo (Input)
    - id: validate_report
      shell: bash
      env:
        REPORT: ${{ inputs.report_file }}
      run: |
        echo "::group::📄 Validation: Report File"
        if [ ! -f "$REPORT" ]; then 
           echo "❌ Error: Report file not found at: '$REPORT'"
           exit 1
        fi
        echo "✅ Report file found."
        echo "::endgroup::"

    # 1.2 - Configuração de Ambiente Git
    - id: git_config
      shell: bash
      env:
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🔧 Git Config: Identity"
        git config user.name "git-report-ops-bot"
        git config user.email "$BOT_EMAIL"
        echo "✅ Identity configured ($BOT_EMAIL)."
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 2: CIRCUIT BREAKER (ANTI-LOOP)
    # ==================================================================

    # 2.0 - Proteção por Nome da Branch
    - id: check_branch
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        PREFIX: ${{ inputs.report_branch_prefix }}
      run: |
        echo "::group::🛡️ Anti-Loop: Branch Name"
        if [[ "$HEAD_REF" == "$PREFIX"* ]]; then
           echo "🛑 Loop Detected: Inside report branch."
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"
        else
           echo "✅ Branch OK."
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 2.1 - Preparação do Histórico (Fetch)
    - id: fetch_history
      if: steps.check_branch.outputs.skip != 'true'
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        echo "::group::📚 Git History: Fetching Context"
        if [ -f .git/shallow ]; then
           echo "⚙️ Shallow repo detected. Unshallowing..."
           git fetch --depth=1 origin "$HEAD_REF" 2>/dev/null || true
        fi
        echo "✅ Context fetched."
        echo "::endgroup::"

    # 2.2 - Proteção por Autor do Commit
    - id: check_author
      if: steps.check_branch.outputs.skip != 'true'
      shell: bash
      env:
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🛡️ Anti-Loop: Commit Author"
        LAST_AUTHOR=$(git log -1 --pretty=format:'%ae')
        
        if [[ "$LAST_AUTHOR" == "$BOT_EMAIL" ]]; then
           echo "🛑 Loop Detected: Last commit by bot."
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"
        else
           echo "✅ Author OK."
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 3: IDEMPOTENCY CHECK
    # ==================================================================

    # 3.0 - Cálculo da Assinatura
    - id: calc_signature
      # IF: Nem branch nem autor bloquearam
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true'
      shell: bash
      env:
        EXTS: ${{ inputs.scan_extensions }}
        EXCLUDE: ${{ inputs.scan_exclude }}
      run: |
        echo "::group::🧮 Idempotency: Calculating Signature"
        set -euo pipefail
        
        ALL_FILES="/tmp/files_all.txt"
        EXT_MATCHES="/tmp/files_extensions.txt"
        FINAL_LIST="/tmp/files_final.txt"
        HASH_LIST="/tmp/object_hashes.txt"

        git ls-tree -r HEAD --name-only > "$ALL_FILES"
        grep -E "\.($EXTS)$" "$ALL_FILES" > "$EXT_MATCHES" || true
        grep -vE "$EXCLUDE" "$EXT_MATCHES" > "$FINAL_LIST" || true

        if [ -s "$FINAL_LIST" ]; then
           xargs -a "$FINAL_LIST" -d '\n' -r git hash-object > "$HASH_LIST"
           SIGNATURE=$(md5sum "$HASH_LIST" | awk '{print $1}')
        else
           SIGNATURE="empty"
        fi

        echo "CODE_SIGNATURE=$SIGNATURE" >> "$GITHUB_ENV"
        echo "🔑 Signature: $SIGNATURE"
        echo "::endgroup::"

    # 3.1 - Preparação do Relatório (Injeção de Metadata)
    - id: prep_report
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true'
      shell: bash
      env:
        REPORT: ${{ inputs.report_file }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
      run: |
        echo "::group::📝 Report: Injecting Metadata"
        TEMP="/tmp/meta_report.md"
        echo "" > "$TEMP"
        echo "> **Content Signature:** $SIGNATURE" >> "$TEMP"
        echo "> **Source SHA:** $HEAD_SHA" >> "$TEMP"
        echo "> **Data:** $(date -u)" >> "$TEMP"
        echo "" >> "$TEMP"
        cat "$REPORT" >> "$TEMP"
        mv "$TEMP" "$REPORT"
        echo "✅ Metadata added."
        echo "::endgroup::"

    # 3.2 - Busca de Histórico (Idempotência)
    - id: check_history
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true'
      shell: bash
      env:
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        echo "::group::🕵️ Idempotency: History Search"
        set -euo pipefail

        if [ -f .git/shallow ]; then git fetch --unshallow 2>/dev/null || true; fi
        git fetch --all --quiet
        
        SEARCH="> **Content Signature:** $SIGNATURE"
        FOUND=$(git grep -I -F -l "$SEARCH" $(git rev-list --all --author="$BOT_EMAIL") -- "*.md" 2>/dev/null | head -n 1 || true)

        if [ -n "$FOUND" ]; then
           echo "✅ Match found: $FOUND"
           echo "found=true" >> "$GITHUB_OUTPUT"
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_IDEMPOTENT" >> "$GITHUB_OUTPUT"
           SHA=$(echo "$FOUND" | cut -d':' -f1)
           echo "commit_sha=$SHA" >> "$GITHUB_OUTPUT"
        else
           echo "📝 No match found. New content."
           echo "found=false" >> "$GITHUB_OUTPUT"
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 3.3 - Recuperação de URL
    - id: recover_url
      # IF: Se a busca histórica achou algo (found=true)
      if: steps.check_history.outputs.found == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        COMMIT_SHA: ${{ steps.check_history.outputs.commit_sha }}
        PREFIX: ${{ inputs.report_branch_prefix }}
      run: |
        echo "::group::🔗 Idempotency: Recovering URL"
        TARGET=$(git branch -r --contains "$COMMIT_SHA" | grep "$PREFIX" | head -n 1 | sed 's/^[[:space:]]*origin\///' | xargs || true)
        
        if [ -n "$TARGET" ]; then
           URL=$(gh pr list --head "$TARGET" --state open --json url -q .[0].url || true)
           if [ -n "$URL" ] && [ "$URL" != "null" ]; then
              echo "✅ URL Recovered: $URL"
              echo "pr_url=$URL" >> "$GITHUB_OUTPUT"
           fi
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 4: PUBLISH (BRANCH & PR)
    # ==================================================================

    # 4.0 - Operações Git
    - id: git_push
      # IF: Nenhum bloqueio anterior (Circuit 1 & 2 + Idempotency)
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true' && steps.check_history.outputs.skip != 'true'
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        PREFIX: ${{ inputs.report_branch_prefix }}
        REPORT: ${{ inputs.report_file }}
      run: |
        echo "::group::🚀 Git: Pushing"
        REPORT_BRANCH="${PREFIX}/${HEAD_REF}"
        git checkout "$HEAD_REF"
        git checkout -B "$REPORT_BRANCH"
        git add "$REPORT"
        git commit -m "docs: automated report update [skip ci]"
        git push -f origin "$REPORT_BRANCH"
        echo "branch=$REPORT_BRANCH" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # 4.1 - Construção do Corpo (Template)
    - id: build_body
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true' && steps.check_history.outputs.skip != 'true'
      shell: bash
      env:
        PR_NUM: ${{ github.event.pull_request.number }}
        HEAD_REF: ${{ github.head_ref }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        USER_BODY: ${{ inputs.pr_body }}
        CUSTOM_TEMPLATE: ${{ inputs.pr_template_path }}
        DEFAULT_TEMPLATE: ${{ github.action_path }}/templates/pr-body-default.md
      run: |
        echo "::group::📝 PR: Building Body"
        BODY_FILE="/tmp/pr_description.md"
        export DATE=$(date -u)
        
        if [[ -n "$CUSTOM_TEMPLATE" && -f "$CUSTOM_TEMPLATE" ]]; then
           TEMPLATE_SOURCE="$CUSTOM_TEMPLATE"
        else
           TEMPLATE_SOURCE="$DEFAULT_TEMPLATE"
        fi
        
        envsubst < "$TEMPLATE_SOURCE" > "$BODY_FILE"
        
        # Injeção Obrigatória da Assinatura (CORRIGIDO)
        echo "" >> "$BODY_FILE"
        echo "" >> "$BODY_FILE"
        
        echo "body_file=$BODY_FILE" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # 4.2 - Gerenciamento da PR
    - id: publish
      if: steps.check_branch.outputs.skip != 'true' && steps.check_author.outputs.skip != 'true' && steps.check_history.outputs.skip != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        HEAD_REF: ${{ github.head_ref }}
        REPORT_BRANCH: ${{ steps.git_push.outputs.branch }}
        TITLE: ${{ inputs.pr_title }}
        BODY_FILE: ${{ steps.build_body.outputs.body_file }}
      run: |
        echo "::group::📡 API: PR Management"
        
        gh pr create \
          --base "$HEAD_REF" \
          --head "$REPORT_BRANCH" \
          --title "$TITLE" \
          --body-file "$BODY_FILE" || true
          
        PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
        gh pr edit "$PR_URL" --body-file "$BODY_FILE" || true
        
        echo "✅ PR Link: $PR_URL"
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "status=PUBLISHED" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 5: CONTROLLER (OUTPUT SUMMARY)
    # ==================================================================
    - id: logic_controller
      shell: bash
      if: always()
      env:
        # Status dos Circuit Breakers
        S_BRANCH: ${{ steps.check_branch.outputs.reason }}
        S_AUTHOR: ${{ steps.check_author.outputs.reason }}
        # Status de Idempotência
        S_IDEM: ${{ steps.check_history.outputs.reason }}
        # Status de Publicação
        S_PUB: ${{ steps.publish.outputs.status }}
        # URLs (Recuperada ou Criada)
        URL_REC: ${{ steps.recover_url.outputs.pr_url }}
        URL_PUB: ${{ steps.publish.outputs.pr_url }}
      run: |
        # Prioridade de Status
        if [ -n "$S_PUB" ]; then FINAL_STATUS="$S_PUB";
        elif [ -n "$S_IDEM" ]; then FINAL_STATUS="$S_IDEM";
        elif [ -n "$S_AUTHOR" ]; then FINAL_STATUS="$S_AUTHOR";
        elif [ -n "$S_BRANCH" ]; then FINAL_STATUS="$S_BRANCH";
        else FINAL_STATUS="UNKNOWN"; fi
        
        # Prioridade de URL (Se publicou, usa a nova. Se recuperou, usa a antiga)
        if [ -n "$URL_PUB" ]; then FINAL_URL="$URL_PUB";
        else FINAL_URL="$URL_REC"; fi

        echo "status=$FINAL_STATUS" >> "$GITHUB_OUTPUT"
        echo "pr_url=$FINAL_URL" >> "$GITHUB_OUTPUT"
