# Malnati/git-report-ops@v1.1.1
name: "Git Report Ops"
description: "Engine GitOps v1.1.1: Fix de newlines e formatação aprimorada da PR."
author: "Ricardo Malnati"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  token:
    description: "GitHub token."
    required: true
  report_file:
    description: "Arquivo Markdown para publicar."
    required: true
  scan_extensions:
    description: "Extensões para assinatura."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  scan_exclude:
    description: "Caminhos ignorados."
    required: false
    default: "node_modules|dist|build|.git|.github"
  report_branch_prefix:
    description: "Prefixo da branch."
    required: false
    default: "audit/report"
  pr_title:
    description: "Título da PR."
    required: false
    default: "🛡️ Automated Audit Report"
  pr_body:
    description: "Corpo base da PR."
    required: false
    default: "Relatório de auditoria gerado automaticamente."
  bot_email:
    description: "Email do bot."
    required: false
    default: "git-report-ops@users.noreply.github.com"

outputs:
  pr_url:
    description: "URL da Pull Request."
    value: ${{ steps.publish.outputs.pr_url }}
  status:
    description: "Status da operação."
    value: ${{ steps.logic_controller.outputs.status }}

runs:
  using: "composite"
  steps:
    # ... [STEP 0, 1 e 2 permanecem IDÊNTICOS à v1.1.0] ...
    # ... (Copie os steps 0, 1 e 2 da versão anterior ou mantenha se já tiver) ...
    
    # Vou replicar apenas o STEP 0, 1 e 2 resumidos para contexto, 
    # mas a mudança real é no STEP 3 abaixo.
    
    - id: setup
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPORT: ${{ inputs.report_file }}
      run: |
        if [ -z "$TOKEN" ]; then echo "❌ Token missing."; exit 1; fi
        if [ ! -f "$REPORT" ]; then echo "❌ File not found."; exit 1; fi
        git config user.name "git-report-ops-bot"
        git config user.email "${{ inputs.bot_email }}"

    - id: circuit_breaker
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        PREFIX: ${{ inputs.report_branch_prefix }}
        BOT_EMAIL: ${{ inputs.bot_email }}
      run: |
        if [[ "$HEAD_REF" == "$PREFIX"* ]]; then echo "skip=true" >> "$GITHUB_OUTPUT"; echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"; exit 0; fi
        if [ -f .git/shallow ]; then git fetch --depth=1 origin "$HEAD_REF" 2>/dev/null || true; fi
        LAST=$(git log -1 --pretty=format:'%ae')
        if [[ "$LAST" == "$BOT_EMAIL" ]]; then echo "skip=true" >> "$GITHUB_OUTPUT"; echo "reason=SKIPPED_LOOP" >> "$GITHUB_OUTPUT"; exit 0; fi
        echo "skip=false" >> "$GITHUB_OUTPUT"

    - id: idempotency
      if: steps.circuit_breaker.outputs.skip != 'true'
      shell: bash
      env:
        EXTS: ${{ inputs.scan_extensions }}
        EXCLUDE: ${{ inputs.scan_exclude }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        REPORT: ${{ inputs.report_file }}
      run: |
        SIGNATURE=$(git ls-tree -r HEAD --name-only | grep -E "\.($EXTS)$" | grep -vE "$EXCLUDE" | xargs -d '\n' git hash-object 2>/dev/null | md5sum | awk '{print $1}' || echo "empty")
        echo "CODE_SIGNATURE=$SIGNATURE" >> "$GITHUB_ENV"
        
        TEMP="/tmp/meta_report.md"
        echo "" > "$TEMP"
        echo "> **Content Signature:** $SIGNATURE" >> "$TEMP"
        echo "> **Source SHA:** $HEAD_SHA" >> "$TEMP"
        echo "> **Data:** $(date -u)" >> "$TEMP"
        echo "" >> "$TEMP"
        cat "$REPORT" >> "$TEMP"
        mv "$TEMP" "$REPORT"

        if [ -f .git/shallow ]; then git fetch --unshallow 2>/dev/null || true; fi
        git fetch --all --quiet
        SEARCH="> **Content Signature:** $SIGNATURE"
        FOUND=$(git grep -I -F -l "$SEARCH" $(git rev-list --all --author="$BOT_EMAIL") -- "*.md" 2>/dev/null | head -n 1 || true)

        if [ -n "$FOUND" ]; then
           echo "skip=true" >> "$GITHUB_OUTPUT"
           echo "reason=SKIPPED_IDEMPOTENT" >> "$GITHUB_OUTPUT"
           SHA=$(echo "$FOUND" | cut -d':' -f1)
           BRANCH=$(git branch -r --contains "$SHA" | grep "origin/ops/" | head -n 1 | sed 's/origin\///' | xargs)
           if [ -n "$BRANCH" ]; then
              URL=$(gh pr list --head "$BRANCH" --json url -q .[0].url)
              [ -n "$URL" ] && echo "pr_url=$URL" >> "$GITHUB_OUTPUT"
           fi
        else
           echo "skip=false" >> "$GITHUB_OUTPUT"
        fi

    # ------------------------------------------------------------------
    # STEP 3: PUBLISH (CORRIGIDO - SEM \n LITERAL)
    # ------------------------------------------------------------------
    - id: publish
      if: steps.circuit_breaker.outputs.skip != 'true' && steps.idempotency.outputs.skip != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPORT_FILE: ${{ inputs.report_file }}
        HEAD_REF: ${{ github.head_ref }}
        PR_NUM: ${{ github.event.pull_request.number }}
        PREFIX: ${{ inputs.report_branch_prefix }}
        TITLE: ${{ inputs.pr_title }}
        USER_BODY: ${{ inputs.pr_body }}
        SIGNATURE: ${{ env.CODE_SIGNATURE }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "::group::🚀 Publishing Report"
        
        REPORT_BRANCH="${PREFIX}/${HEAD_REF}"
        
        # Git Ops
        git checkout "$HEAD_REF"
        git checkout -B "$REPORT_BRANCH"
        git add "$REPORT_FILE"
        git commit -m "docs: automated report update [skip ci]"
        git push -f origin "$REPORT_BRANCH"
        
        # --- CRIAÇÃO DO CORPO EM ARQUIVO (CORREÇÃO DE NEWLINES) ---
        BODY_FILE="/tmp/pr_body.md"
        
        cat <<EOF > "$BODY_FILE"
        $USER_BODY

        ---
        ### 🛡️ Metadados de Rastreabilidade
        > Esta PR contém artefatos gerados automaticamente para a revisão da PR original.

        | 🏷️ Chave | ℹ️ Valor |
        | :--- | :--- |
        | **PR Origem** | #$PR_NUM (\`$HEAD_REF\`) |
        | **Commit Base** | \`$HEAD_SHA\` |
        | **Assinatura** | \`$SIGNATURE\` |
        | **Data (UTC)** | $(date -u) |

        EOF
        # ----------------------------------------------------------
        
        echo "📡 Managing Pull Request..."
        
        # Tenta criar
        gh pr create \
          --base "$HEAD_REF" \
          --head "$REPORT_BRANCH" \
          --title "$TITLE" \
          --body-file "$BODY_FILE" || true  # <-- Usando --body-file
          
        PR_URL=$(gh pr view "$REPORT_BRANCH" --json url -q .url)
        
        # Tenta atualizar (garante body novo)
        gh pr edit "$PR_URL" --body-file "$BODY_FILE" || true # <-- Usando --body-file
        
        echo "✅ PR Link: $PR_URL"
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "status=PUBLISHED" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # ... [STEP 4 - Controller - Igual] ...
    - id: logic_controller
      shell: bash
      if: always()
      env:
        S1: ${{ steps.circuit_breaker.outputs.reason }}
        S2: ${{ steps.idempotency.outputs.reason }}
        S3: ${{ steps.publish.outputs.status }}
      run: |
        FINAL_STATUS="UNKNOWN"
        if [ -n "$S3" ]; then FINAL_STATUS="$S3";
        elif [ -n "$S2" ]; then FINAL_STATUS="$S2";
        elif [ -n "$S1" ]; then FINAL_STATUS="$S1";
        fi
        echo "status=$FINAL_STATUS" >> "$GITHUB_OUTPUT"
