# Malnati/git-report-ops@v1.3.46
name: "Git Pull Request Ops"
description: "Engine de auditoria que assina o conteúdo, detecta renames e envia notificações padronizadas para Pull Requests."
author: "Ricardo Malnati"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  token:
    description: "GitHub token."
    required: true
  pr_number:
    description: "Número da Pull Request origem, se será usada para descobrir qual é a branch destino da nova PR."
    required: true
  attached_file_path:
    description: "Arquivo anexo ao repositório. (report.csv)"
    required: true
  branch_convention_prefix:
    required: false
    default: "ops/files"
  pr_title:
    required: false
    default: "🛡️ Automated Pull Request"
  pr_template_path:
    required: true
    description: "Arquivo anexo ao repositório. (pr-template.md)"
  timeline_template_path:
    required: true
    description: "Arquivo anexo ao repositório. (timeline-template.md)"
  bot_name:
    description: "Nome do bot usado nos commits."
    required: false
    default: "git-pr-ops-bot"
  bot_email:
    required: false
    default: "git-pr-ops@users.noreply.github.com"
    
runs:
  using: "composite"
  steps:
    - id: step_validate_inputs
      name: "🔧 Setup & Input Validation"
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        ATTACHED_FILE_PATH: ${{ inputs.attached_file_path }}
        CALLER_ID: ${{ inputs.caller_id }}
        BRANCH_CONVENTION_PREFIX: ${{ inputs.branch_convention_prefix }}
        PR_TITLE: ${{ inputs.pr_title }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        PR_TEMPLATE_PATH: ${{ inputs.pr_template_path }}
        TIMELINE_TEMPLATE_PATH: ${{ inputs.timeline_template_path }}
      run: |
        echo "::group::🔧 Setup & Input Validation"

        if [ -z "$TOKEN" ]; then
          echo "❌ [token] Obrigatório e não informado. Sem este token a Action não consegue chamar a API do GitHub (gh CLI, criação/edição de PR e comentários)."
          echo "   ➜ Defina 'token' com 'secrets.GITHUB_TOKEN' ou um PAT com permissões de leitura/escrita em PRs."
          exit 1
        else
          echo "✅ [token] Informado. A Action poderá criar/atualizar PRs e publicar comentários."
        fi
        
        if [ -z "$PR_NUMBER" ]; then
          echo "❌ [pr_number] Obrigatório e não informado. Sem este pr_number a Action não consegue descobrir qual é a branch destino da nova PR."
          echo "   ➜ Defina 'pr_number' com 'N' ou '#N' da PR origem."
          exit 1
        else
          echo "✅ [pr_number] Informado. A Action descobrirá dinamicamente qual é a branch destino da nova PR."
        fi

        if [ -z "$ATTACHED_FILE_PATH" ]; then
          echo "❌ [attached_file_path] Caminho não informado. A Action precisa de um arquivo para anexar ao PR."
          echo "   ➜ Gere o relatório no job anterior e passe o caminho em 'attached_file_path' (ex.: 'reports/pmd-report.md')."
          exit 1
        elif [ ! -f "$ATTACHED_FILE_PATH" ]; then
          echo "❌ [attached_file_path] Arquivo '$ATTACHED_FILE_PATH' não encontrado."
          echo "   ➜ Verifique o caminho informado em 'attached_file_path' e garanta que o arquivo é criado antes desta Action."
          exit 1
        else
          echo "✅ [attached_file_path] Encontrado em '$ATTACHED_FILE_PATH'. Será usado como base do arquivo publicado."
        fi

        if [ -z "$PR_TEMPLATE_PATH" ]; then
          echo "❌  [pr_template_path] Não informado."
          echo "   ➜ Defina 'pr_template_path' com o caminho de um template customizado para personalizar o corpo do PR."
          exit 1
        elif [ ! -f "$PR_TEMPLATE_PATH" ]; then
          echo "❌ [pr_template_path] Arquivo '$PR_TEMPLATE_PATH' não encontrado."
          echo "   ➜ Verifique o caminho informado em 'attached_file_path' e garanta que o arquivo é criado antes desta Action."
          exit 1
        else
          echo "✅ [pr_template_path] Encontrado em '$PR_TEMPLATE_PATH'. Será usado para exibir a descrição da Pull Request."
        fi

        if [ -z "$TIMELINE_TEMPLATE_PATH" ]; then
          echo "❌  [timeline_template_path] Não informado."
          echo "   ➜ Defina 'timeline_template_path' com o caminho de um template customizado para personalizar a mensqgem do timeline na PR."
          exit 1
        elif [ ! -f "$TIMELINE_TEMPLATE_PATH" ]; then
          echo "❌ [timeline_template_path] Arquivo '$TIMELINE_TEMPLATE_PATH' não encontrado."
          echo "   ➜ Verifique o caminho informado em 'timeline_template_path' e garanta que o arquivo é criado antes desta Action."
          exit 1
        else
          echo "✅ [timeline_template_path] Encontrado em '$TIMELINE_TEMPLATE_PATH'. Será usado para exibir a mensagem no timeline da Pull Request."
        fi

        if [ -z "$BRANCH_CONVENTION_PREFIX" ]; then
          echo "ℹ️ [branch_convention_prefix] Não informado. Branches de relatório serão criados sem prefixo dedicado, podendo conflitar com branches de desenvolvimento."
          echo "   ➜ Defina um prefixo para isolar branches de relatório: '<prefix>/<branch_origem>'."
        else
          echo "ℹ️ [branch_convention_prefix] Usando prefixo: '<prefix>/<sufixo_commit>'."
          echo "   ➜ Os branches de relatório serão criados como '<prefix>/<sufixo_commit>'."
        fi

        if [ -z "$PR_TITLE" ]; then
          echo "ℹ️ [pr_title] Não informado. O PR poderá ser criado sem título claro, dificultando a leitura na lista de PRs."
          echo "   ➜ Defina 'pr_title' com um título descritivo (ex.: '🛡️ Automated Pull Request')."
        else
          echo "ℹ️ [pr_title] Título configurado como: '$PR_TITLE'."
          echo "   ➜ Este valor será usado como título dos PRs de relatório."
        fi

        if [ -z "$BOT_EMAIL" ]; then
          echo "ℹ️ [bot_email] Não informado. O git usará o email padrão do ambiente e isso pode quebrar a proteção de loop baseada no autor."
          echo "   ➜ Defina 'bot_email' (ex.: 'git-pr-ops@users.noreply.github.com') para: "
          echo "      - identificar os commits do bot; "
          echo "      - permitir que o circuito anti-loop funcione corretamente."
        else
          echo "ℹ️ [bot_email] Usando: '$BOT_EMAIL'."
          echo "   ➜ Este email será configurado como autor dos commits e usado na verificação de loops."
        fi
        
        echo "✅ Input validation complete."
        echo "::endgroup::"
      
    - id: pr_info
      name: "🔍 Obter informações da PR de origem"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        set -euo pipefail
    
        gh auth status || gh auth login --with-token <<<"$GH_TOKEN"
    
        PR_JSON=$(gh pr view "$PR_NUMBER" --json url,title,headRefName,headRefOid,baseRefName,baseRefOid)
    
        PR_URL=$(echo "$PR_JSON" | jq -r '.url')
        PR_TITLE=$(echo "$PR_JSON" | jq -r '.title')
    
        DEST_BRANCH_NAME=$(echo "$PR_JSON" | jq -r '.baseRefName')
        DEST_BRANCH_SHA=$(echo "$PR_JSON" | jq -r '.baseRefOid')
    
        SOURCE_BRANCH_NAME=$(echo "$PR_JSON" | jq -r '.headRefName')
        SOURCE_BRANCH_SHA=$(echo "$PR_JSON" | jq -r '.headRefOid')
    
        echo "PR_URL=$PR_URL"
        echo "PR_TITLE=$PR_TITLE"
        echo "DEST_BRANCH_NAME=$DEST_BRANCH_NAME"
        echo "DEST_BRANCH_SHA=$DEST_BRANCH_SHA"
        echo "SOURCE_BRANCH_NAME=$SOURCE_BRANCH_NAME"
        echo "SOURCE_BRANCH_SHA=$SOURCE_BRANCH_SHA"
    
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "pr_title=$PR_TITLE" >> "$GITHUB_OUTPUT"
        echo "dest_branch_name=$DEST_BRANCH_NAME" >> "$GITHUB_OUTPUT"
        echo "dest_branch_sha=$DEST_BRANCH_SHA" >> "$GITHUB_OUTPUT"
        echo "source_branch_name=$SOURCE_BRANCH_NAME" >> "$GITHUB_OUTPUT"
        echo "source_branch_sha=$SOURCE_BRANCH_SHA" >> "$GITHUB_OUTPUT"

    - name: "🔁 Encontrar PRs derivadas"
      id: derivated_prs_finder
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        SOURCE_BRANCH: ${{ steps.pr_info.outputs.source_branch_name }}
      run: |
        set -euo pipefail
    
        gh auth status || gh auth login --with-token <<<"$GH_TOKEN"
    
        if [ -z "$SOURCE_BRANCH" ]; then
          echo "⚠ SOURCE_BRANCH vazio. Nada a fazer."
          exit 0
        fi
    
        PR_LIST=$(gh pr list \
          --state open \
          --base "$SOURCE_BRANCH" \
          --json number,url,headRefName,baseRefName)
    
        COUNT=$(echo "$PR_LIST" | jq 'length')
    
        echo "🔍 PRs derivadas abertas com destino em '$SOURCE_BRANCH': total=$COUNT"
    
        echo "$PR_LIST" | jq -c '.[]' | while read -r pr; do
          NUM=$(echo "$pr" | jq -r '.number')
          URL=$(echo "$pr" | jq -r '.url')
          HEAD=$(echo "$pr" | jq -r '.headRefName')
          BASE=$(echo "$pr" | jq -r '.baseRefName')
    
          echo "- #$NUM $URL"
          echo "  head: $HEAD"
          echo "  base: $BASE"
        done
    
        echo "derived_count=$COUNT" >> "$GITHUB_OUTPUT"
        echo "derived_prs_json=$PR_LIST" >> "$GITHUB_OUTPUT"
    
    - id: branch_convention
      name: "🪾 Branch Convention"
      shell: bash
      env:
        BRANCH_CONVENTION_PREFIX: ${{ inputs.branch_convention_prefix }}
      run: |
        set -euo pipefail
        echo "::group::🪾 Define branch convention"
    
        if [ -z "${BRANCH_CONVENTION_PREFIX:-}" ]; then
          BRANCH_CONVENTION_PREFIX="ops/report/latest"
        fi
    
        git fetch --all --prune
    
        LATEST_SHA="$(git rev-parse HEAD)"
        CUSTOM_SUFFIX="${LATEST_SHA: -10}"
    
        BRANCH_CONVENTION="${BRANCH_CONVENTION_PREFIX}/${CUSTOM_SUFFIX}"
    
        echo "prefix: $BRANCH_CONVENTION_PREFIX"
        echo "latest_sha: $LATEST_SHA"
        echo "custom_suffix: $CUSTOM_SUFFIX"
        echo "branch_convention: $BRANCH_CONVENTION"
    
        echo "branch_convention=$BRANCH_CONVENTION" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"
        
    - id: commit_attached_file
      name: "📝 Commit File"
      shell: bash
      env:
        ATTACHED_FILE_PATH: ${{ inputs.attached_file_path }}
        BRANCH_CONVENTION: ${{ steps.branch_convention.outputs.branch_convention }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        BOT_NAME: ${{ inputs.bot_name }}
      run: |
        set -euo pipefail
        echo "::group::📝 Commit file"
        echo "branch_convention: $BRANCH_CONVENTION"
        echo "attached_file_path: $ATTACHED_FILE_PATH"

        if [ -z "${BRANCH_CONVENTION:-}" ]; then
          echo "❌ BRANCH_CONVENTION vazio. Verifique o bloco branch_convention."
          echo "::endgroup::"
          exit 1
        fi

        git fetch --all --prune

        if git show-ref --verify --quiet "refs/heads/$BRANCH_CONVENTION"; then
          echo "ℹ Branch já existe localmente: $BRANCH_CONVENTION"
          git checkout "$BRANCH_CONVENTION"
        else
          if git ls-remote --exit-code --heads origin "$BRANCH_CONVENTION" >/dev/null 2>&1; then
            echo "ℹ Branch existe no remoto, criando tracking local: $BRANCH_CONVENTION"
            git checkout -b "$BRANCH_CONVENTION" "origin/$BRANCH_CONVENTION"
          else
            echo "🆕 Criando nova branch a partir do HEAD atual: $BRANCH_CONVENTION"
            git checkout -b "$BRANCH_CONVENTION"
          fi
        fi

        if [ ! -f "$ATTACHED_FILE_PATH" ]; then
          echo "❌ Arquivo de relatório não encontrado: $ATTACHED_FILE_PATH"
          echo "::endgroup::"
          exit 1
        fi

        git config user.email "$BOT_EMAIL"
        if [ -n "${BOT_NAME:-}" ]; then
          git config user.name "$BOT_NAME"
        fi

        git add "$ATTACHED_FILE_PATH"

        if git diff --cached --quiet; then
          echo "⚠️ Nenhuma alteração para commitar em $ATTACHED_FILE_PATH"
          echo "::endgroup::"
          exit 0
        fi

        git commit -m "chore(attach): update attached file"
        git push origin "$BRANCH_CONVENTION"

        COMMIT_SHA="$(git rev-parse HEAD)"
        echo "commit_sha=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
        echo "branch_convention=$BRANCH_CONVENTION" >> "$GITHUB_OUTPUT"
        echo "✅ Attached file commit realizado em $BRANCH_CONVENTION (commit $COMMIT_SHA)"
        echo "::endgroup::"

    - name: "🪄 Exportar variáveis para o PR template"
      id: export_vars_pr_template
      shell: bash
      run: |
        set -euo pipefail
        env | grep -v '^GITHUB_' | while IFS='=' read -r key value; do
          printf '%s=%s\n' "$key" "$value"
          printf '%s=%s\n' "$key" "$value" >> "$GITHUB_ENV"
        done
          
    - name: "📄 Render PR template"
      id: render_pr
      uses: Malnati/template-render@v1.0.1
      with:
        template: ${{ inputs.pr_template_path }}
        output: /tmp/hardcode-pr.md
        
    - id: publish_pr
      name: "🚀 Publishing Pull Request"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        BASE_BRANCH: ${{ steps.pr_info.outputs.source_branch_name }}
        HEAD_BRANCH: ${{ steps.commit_attached_file.outputs.branch_convention }}
        TITLE: ${{ inputs.pr_title }}
        PR_TEMPLATE_PATH: ${{ steps.render_pr.outputs.path }}
      run: |
        set -euo pipefail
        echo "BASE_BRANCH: $BASE_BRANCH"
        echo "HEAD_BRANCH: $HEAD_BRANCH"
        echo "PR_TEMPLATE_PATH: $PR_TEMPLATE_PATH"

        if [ -z "${BASE_BRANCH:-}" ] || [ -z "${HEAD_BRANCH:-}" ]; then
          echo "❌ BASE_BRANCH ou HEAD_BRANCH vazios. Verifique pr_info e commit_attached_file."
          echo "::endgroup::"
          exit 1
        fi

        gh auth status || gh auth login --with-token <<<"$GH_TOKEN"

        gh pr create \
          --base "$BASE_BRANCH" \
          --head "$HEAD_BRANCH" \
          --title "$TITLE" \
          --body-file "$PR_TEMPLATE_PATH"

        PR_URL="$(gh pr view "$HEAD_BRANCH" --json url --jq '.url' || echo "")"

        if [ -z "$PR_URL" ] || [ "$PR_URL" = "null" ]; then
          echo "🔴 Falha ao obter URL da PR recém-criada." >&2
          echo "::endgroup::"
          exit 1
        fi

        echo "PR_URL: $PR_URL"
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "pr_state=OPEN" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    - name: "🪄 Exportar variáveis para o template"
      id: export_vars_timeline_template
      shell: bash
      run: |
        set -euo pipefail
        env | grep -v '^GITHUB_' | while IFS='=' read -r key value; do
          printf '%s=%s\n' "$key" "$value"
          printf '%s=%s\n' "$key" "$value" >> "$GITHUB_ENV"
        done
          
    - name: "📄 Render timeline template"
      id: render_timeline
      uses: Malnati/template-render@v1.0.1
      with:
        template: ${{ inputs.timeline_template_path }}
        output: /tmp/hardcode-timeline.md
          
    - id: timeline_notification
      name: "🔔 Notify over PR Timeline"
      uses: Malnati/pr-comment@v8.0.2
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ inputs.pr_number }}
        template_path: ${{ steps.render_timeline.outputs.path }}
